[package]
name = "hocon"
version = "0.9.0"
authors = ["François Mockers <mockersf@gmail.com>", "Logan McGrath <keywordsalad@thisfieldwas.green>"]
edition = "2018"
description = "Reads HOCON configuration files"
repository = "https://github.com/keywordsalad/hocon.rs"
homepage = "https://github.com/keywordsalad/hocon.rs"
documentation = "https://docs.rs/hocon"
keywords = ["hocon", "configuration"]
license = "MIT"
readme = "README.md"

[badges]
travis-ci = { repository = "keywordsalad/hocon.rs" }

[dependencies]
aho-corasick = "1.0.*"
java-properties = "2.0.*"
lazy_static = "1.4.*"
linked-hash-map = "0.5.*"
memchr = "2.5.*"
nom = "4.2"
reqwest = { version = "0.11.*", optional = true, default-features = false, features = [ "blocking", "rustls", "rustls-tls-native-roots" ] }
serde = { version = "1.0.*", optional = true }
serde_path_to_error = "0.1.*"
thiserror = "1.0.*"
uuid = { version = "1.3.*", features = [ "v4" ] }

[dev-dependencies]
criterion = "0.5.*"
insta = "1.29.*"
rand = "0.8.*"
serde = { version = "1.0.*", features = [ "derive" ] }
serde_json = "1.0.*"
test-generator = "0.3.*"

[features]
default = [ "test-snapshot", "serde-support", "url-support" ]
serde-support = [ "serde" ]
test-snapshot = []
url-support = [ "reqwest" ]

[[bench]]
name = "parse"
harness = false
